version: '3.4'

services:
  pgdb:
    container_name: psql-11-backend_db
    image: mdillon/postgis:11-alpine
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
    name: postgres-data
